openapi: 3.0.3
servers:
  - url: https://demo.secapi.cloud/providers/seca.load-balancer
    description: Path Schema
  - url: https://load-balancer.seca.demo.secapi.cloud
    description: DNS Schema
info:
  title: Sovereign European Cloud API - Load Balancer
  description: |
    The Load Balancer API provides access to Network Load Balancer resources.
    This API is part of the Sovereign European Cloud API.
  version: v1
security:
  - bearerAuth: []
tags:
  - name: LoadBalancer
    description: LoadBalancer management
paths:
  # LoadBalancer Resources
  /v1/tenants/{id}/workspaces/{workspace}/network-load-balancers:
    get:
      tags:
        - LoadBalancer
      summary: List all NetworkLoadBalancers
      operationId: listNetworkLoadBalancers
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}/workspaces/{workspaceName}"]
            resources: ["seca.network/network-load-balancers"]
            verbs: ["list"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: workspace
          in: path
          required: true
          schema:
            type: string
        - $ref: './schemas/parameters.yaml#/parameters/labelSelector'
        - $ref: './schemas/parameters.yaml#/parameters/limitParam'
        - $ref: './schemas/parameters.yaml#/parameters/skipTokenParam'
        - $ref: './schemas/parameters.yaml#/parameters/acceptHeader'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: './schemas/load-balancer.yaml#/NetworkLoadBalancer'
                  metadata:
                    type: object
                    properties:
                      skipToken:
                        type: string
                        description: Opaque cursor to get the next page. Field is omitted when there are no more pages available.

  /v1/tenants/{id}/workspaces/{workspace}/network-load-balancers/{network-load-balancer-name}:
    get:
      tags:
        - LoadBalancer
      summary: Get a Network Load Balancer
      operationId: getNetworkLoadBalancer
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}/workspaces/{workspaceName}"]
            resources: ["seca.network/network-load-balancers/{network-load-balancer-name}"]
            verbs: ["get"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: workspace
          in: path
          required: true
          schema:
            type: string
        - name: network-load-balancer-name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/load-balancer.yaml#/NetworkLoadBalancer'
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

    put:
      tags:
        - LoadBalancer
      summary: Create or update a specific Network-Load-Balancer
      operationId: createOrUpdateNetworkLoadBalancer
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}/workspaces/{workspaceName}"]
            resources: ["seca.network/network-load-balancers/{network-load-balancer-name}"]
            verbs: ["create","update"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: workspace
          in: path
          required: true
          schema:
            type: string
        - name: network-load-balancer-name
          in: path
          required: true
          schema:
            type: string
        - $ref: './schemas/parameters.yaml#/parameters/ifUnmodifiedSince'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/load-balancer.yaml#/NetworkLoadBalancer'
      responses:
        '202':
          description: NetworkLoadBalancer updated or created
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '412':
          $ref: './schemas/errors.yaml#/responses/Error412'
        '422':
          $ref: './schemas/errors.yaml#/responses/Error422'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

    delete:
      tags:
        - LoadBalancer
      summary: Delete a specific NetworkLoadBalancer
      operationId: deleteNetworkLoadBalancer
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}/workspaces/{workspaceName}"]
            resources: ["seca.network/network-load-balancers/{network-load-balancer-name}"]
            verbs: ["delete"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: workspace
          in: path
          required: true
          schema:
            type: string
        - name: network-load-balancer-name
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: NetworkLoadBalancer deleted
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

components:
  securitySchemes:
    $ref: './schemas/security.yaml#/securitySchemes'
