openapi: 3.0.3
info:
  title: Sovereign European Cloud API
  version: 0.5.3
  license:
    name: "Proprietary - All Rights Reserved"
  description: |
    API for managing cloud resources

    For this intermediate version, the scope 
    * the focus is on IaaS Layer 3 Network
    * does not include rights management or rbac - every provider can use its own authentication/authorization protocol 
    * does not include PaaS features
    * does not include loadbalancers, nat, vpn, and other network features

    ![API Diagram](https://x.frei-services.net/api-diagram.png)
paths:
  # regions
  /v1beta/regions:
    $ref: './paths/regions.yaml#/~1regions'

  # Network resources - VPC and its resources
  /v1beta1/workspaces/{workspace}/providers/network/vpcs:
    $ref: './paths/vpc.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}:
    $ref: './paths/vpc.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}/subnets:
    $ref: './paths/subnets.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1subnets'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}/subnets/{name}:
    $ref: './paths/subnets.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1subnets~1{name}'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}/routing-tables:
    $ref: './paths/routing-tables.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1routing-tables'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}/routing-tables/{name}:
    $ref: './paths/routing-tables.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1routing-tables~1{name}'
  /v1beta1/workspaces/{workspace}/providers/network/vpcs/{vpc}/security-groups:
    $ref: './paths/security-groups.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1security-groups'
  /v1beta/workspace/{workspace}/providers/network/vpcs/{vpc}/security-groups/{name}:
    $ref: './paths/security-groups.yaml#/~1workspace~1{workspace}~1providers~1network~1vpcs~1{vpc}~1security-groups~1{name}'

  # Workspace resources with provider namespace
  /v1beta1/workspaces/{workspace}/providers/compute/instances:
    $ref: './paths/instances.yaml#/~1workspace~1{workspace}~1providers~1compute~1instances'
  /v1beta/workspaces/{workspace}/providers/compute/instances/{name}:
    $ref: './paths/instances.yaml#/~1workspace~1{workspace}~1providers~1compute~1instances~1{name}'
  /v1beta1/workspaces/{workspace}/providers/storage/block-storage:
    $ref: './paths/block-storage.yaml#/~1workspace~1{workspace}~1providers~1storage~1block-storage'
  /v1beta/workspaces/{workspace}/providers/storage/block-storage/{name}:
    $ref: './paths/block-storage.yaml#/~1workspace~1{workspace}~1providers~1storage~1block-storage~1{name}'
  
  # Block storage snapshots
  /v1beta/workspaces/{workspace}/providers/storage/block-storage/{name}/snapshots:
    $ref: './paths/block-storage.yaml#/~1workspace~1{workspace}~1providers~1storage~1block-storage~1{name}~1snapshots'
  /v1beta/workspaces/{workspace}/providers/storage/block-storage/{name}/snapshots/{snapshotName}:
    $ref: './paths/block-storage.yaml#/~1workspace~1{workspace}~1providers~1storage~1block-storage~1{name}~1snapshots~1{snapshotName}'

  # Additional resources (not under workspace)
  /v1beta/images:
    $ref: './paths/images.yaml#/~1images'
  /v1beta/images/{name}:
    $ref: './paths/images.yaml#/~1images~1{name}'

components:
  schemas:
    VPC:
      $ref: './schemas/vpc.yaml#/VPC'
    Subnet:
      $ref: './schemas/subnet.yaml#/Subnet'
    NIC:
      $ref: './schemas/nic.yaml#/NIC'
    SecurityGroup:
      $ref: './schemas/security-group.yaml#/SecurityGroup'
    Instance:
      $ref: './schemas/instance.yaml#/Instance'
    BlockStorage:
      $ref: './schemas/block-storage.yaml#/BlockStorage'
    BlockStorageSnapshot:
      $ref: './schemas/block-storage.yaml#/BlockStorageSnapshot'
    Image:
      $ref: './schemas/image.yaml#/Image'
    Error:
      $ref: './schemas/error_schemas.yaml#/Error'
    ErrorDetail:
      $ref: './schemas/error_schemas.yaml#/ErrorDetail'
    Error400:
      $ref: './schemas/error_schemas.yaml#/Error400'
    Error401:
      $ref: './schemas/error_schemas.yaml#/Error401'
    Error403:
      $ref: './schemas/error_schemas.yaml#/Error403'
    Error404:
      $ref: './schemas/error_schemas.yaml#/Error404'
    Error412:
      $ref: './schemas/error_schemas.yaml#/Error412'
    Error422:
      $ref: './schemas/error_schemas.yaml#/Error422'
    Error500:
      $ref: './schemas/error_schemas.yaml#/Error500'
    Route:
      $ref: './schemas/routing-table.yaml#/Route'
    RoutingTable:
      $ref: './schemas/routing-table.yaml#/RoutingTable'
  responses:
    Error400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    Error401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401'
    Error403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error403'
    Error404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error404'
    Error412:
      description: Precondition Failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error412'
    Error422:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error422'
    Error500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error500'
