openapi: 3.0.3
info:
  title: Sovereign European Cloud API
  version: 0.5.1
  license:
    name: "Proprietary - All Rights Reserved"
  description: |
    API for managing cloud resources

    For this intermediate version, the scope 
    * the focus is on IaaS Layer 3 Network
    * does not include rights management or rbac - every provider can use its own authentication/authorization protocol 
    * does not include PaaS features
    * does not include loadbalancers, nat, vpn, and other network features

    ![API Diagram](https://x.frei-services.net/api-diagram.png)
paths:
  # regions
  /regions:
    $ref: './paths/regions.yaml#/~1regions'

  # Network resources
  /vpcs:
    $ref: './paths/vpc.yaml#/~1vpcs'
  /vpcs/{vpc}:
    $ref: './paths/vpc.yaml#/~1vpcs~1{vpc}'
  /vpcs/{vpc}/subnets:
    $ref: './paths/subnets.yaml#/~1vpc~1{vpc}~1subnets'
  /vpcs/{vpc}/subnets/{name}:
    $ref: './paths/subnets.yaml#/~1vpc~1{vpc}~1subnets~1{name}'
  /vpcs/{vpc}/security-groups:
    $ref: './paths/security-groups.yaml#/~1vpc~1{vpc}~1security-groups'
  /vpcs/{vpc}/security-groups/{name}:
    $ref: './paths/security-groups.yaml#/~1vpc~1{vpc}~1security-groups~1{name}'
  /vpcs/{vpc}/servers:
    $ref: './paths/servers.yaml#/~1vpc~1{vpc}~1servers'
  /vpcs/{vpc}/servers/{name}:
    $ref: './paths/servers.yaml#/~1vpc~1{vpc}~1servers~1{name}'
  /vpcs/{vpc}/volumes:
    $ref: './paths/volumes.yaml#/~1vpc~1{vpc}~1volumes'
  /vpcs/{vpc}/volumes/{name}:
    $ref: './paths/volumes.yaml#/~1vpc~1{vpc}~1volumes~1{name}'
  
  # New paths for volume snapshots
  /vpcs/{vpc}/volumes/{name}/snapshots:
    $ref: './paths/volumes.yaml#/~1vpc~1{vpc}~1volumes~1{name}~1snapshots'
  /vpcs/{vpc}/volumes/{name}/snapshots/{snapshotName}:
    $ref: './paths/volumes.yaml#/~1vpc~1{vpc}~1volumes~1{name}~1snapshots~1{snapshotName}'
  
  # New paths for server-profile and volume-profile
  /vpcs/{vpc}/server-profile:
    $ref: './paths/profiles.yaml#/~1vpc~1{vpc}~1server-profiles'
  /vpcs/{vpc}/volume-profile:
    $ref: './paths/profiles.yaml#/~1vpc~1{vpc}~1volume-profiles'

  # Additional resources (not under vpc)
  /images:
    $ref: './paths/images.yaml#/~1images'
  /images/{name}:
    $ref: './paths/images.yaml#/~1images~1{name}'

  # Routing Table paths
  /vpcs/{vpc}/routing-tables:
    $ref: './paths/routing-tables.yaml#/~1vpcs~1{vpc}~1routing-tables'
  /vpcs/{vpc}/routing-tables/{name}:
    $ref: './paths/routing-tables.yaml#/~1vpcs~1{vpc}~1routing-tables~1{name}'

components:
  schemas:
    VPC:
      $ref: './schemas/vpc.yaml#/VPC'
    Subnet:
      $ref: './schemas/subnet.yaml#/Subnet'
    NIC:
      $ref: './schemas/nic.yaml#/NIC'
    SecurityGroup:
      $ref: './schemas/security-group.yaml#/SecurityGroup'
    Server:
      $ref: './schemas/server.yaml#/Server'
    Volume:
      $ref: './schemas/volume.yaml#/Volume'
    VolumeSnapshot:
      $ref: './schemas/volume.yaml#/VolumeSnapshot'
    Image:
      $ref: './schemas/image.yaml#/Image'
    ServerProfile:
      $ref: './schemas/resource.yaml#/ServerProfile'
    VolumeProfile:
      $ref: './schemas/resource.yaml#/VolumeProfile'
    Error:
      $ref: './schemas/error_schemas.yaml#/Error'
    ErrorDetail:
      $ref: './schemas/error_schemas.yaml#/ErrorDetail'
    Error400:
      $ref: './schemas/error_schemas.yaml#/Error400'
    Error401:
      $ref: './schemas/error_schemas.yaml#/Error401'
    Error403:
      $ref: './schemas/error_schemas.yaml#/Error403'
    Error404:
      $ref: './schemas/error_schemas.yaml#/Error404'
    Error412:
      $ref: './schemas/error_schemas.yaml#/Error412'
    Error422:
      $ref: './schemas/error_schemas.yaml#/Error422'
    Error500:
      $ref: './schemas/error_schemas.yaml#/Error500'
    Route:
      $ref: './schemas/routing-table.yaml#/Route'
    RoutingTable:
      $ref: './schemas/routing-table.yaml#/RoutingTable'
  responses:
    Error400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    Error401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401'
    Error403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error403'
    Error404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error404'
    Error412:
      description: Precondition Failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error412'
    Error422:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error422'
    Error500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error500'
