openapi: 3.0.3
servers:
  - url: https://demo.secapi.cloud/providers/seca.workspace
    description: Path Schema
  - url: https://workspace.seca.demo.secapi.cloud
    description: DNS Schema
info:
  title: Sovereign European Cloud API - Workspace
  description: |
    The Workspace API provides access to resources that are specific to a tenant's workspace.
    This API is part of the Sovereign European Cloud API.
  version: v1
security:
  - bearerAuth: []
tags:
  - name: Workspace
    description: Workspace management
paths:
  /v1/tenants/{id}/workspaces:
    get:
      tags:
        - Workspace
      summary: List workspaces
      operationId: listWorkspaces
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}"]
            resources: ["seca.core/workspaces"]
            verbs: ["list"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - $ref: './schemas/parameters.yaml#/parameters/labelSelector'
        - $ref: './schemas/parameters.yaml#/parameters/limitParam'
        - $ref: './schemas/parameters.yaml#/parameters/skipTokenParam'
        - $ref: './schemas/parameters.yaml#/parameters/acceptHeader'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: './schemas/workspace.yaml#/Workspace'
                  metadata:
                    type: object
                    properties:
                      skipToken:
                        type: string
                        description: Opaque cursor to get the next page. Field is omitted when there are no more pages available.
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

  /v1/tenants/{id}/workspaces/{name}:
    get:
      tags:
        - Workspace
      summary: Get a specific workspace
      operationId: getWorkspace
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}"]
            resources: ["seca.core/workspaces/{workspaceName}"]
            verbs: ["get"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/workspace.yaml#/Workspace'
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

    put:
      tags:
        - Workspace
      summary: Create or update a workspace
      operationId: createOrUpdateWorkspace
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}"]
            resources: ["seca.core/workspaces/{workspaceName}"]
            verbs: ["create","update"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: name
          in: path
          required: true
          schema:
            type: string
        - $ref: './schemas/parameters.yaml#/parameters/ifUnmodifiedSince'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/workspace.yaml#/Workspace'
      responses:
        '202':
          description: Workspace successfully updated or created
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '412':
          $ref: './schemas/errors.yaml#/responses/Error412'
        '422':
          $ref: './schemas/errors.yaml#/responses/Error422'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

    delete:
      tags:
        - Workspace
      summary: Delete a workspace
      description: >
        Deletes the specified workspace. When a workspace is deleted:
        - All resources within the workspace are permanently deleted
        - This includes all compute, network, storage, and other resources
        - Role assignments specific to this workspace are also deleted
        - Deletion is a cascading operation that removes all associated resources
      operationId: deleteWorkspace
      x-authorization:
        type: hybrid  # Supports both RBAC and ABAC
        policies:
          - type: RBAC
            scopes: ["tenants/{tenantId}"]
            resources: ["seca.core/workspaces/{workspaceName}"]
            verbs: ["delete"]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Tenant ID
        - name: name
          in: path
          required: true
          schema:
            type: string
        - $ref: './schemas/parameters.yaml#/parameters/ifUnmodifiedSince'
      responses:
        '202':
          description: Workspace deletion accepted
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '412':
          $ref: './schemas/errors.yaml#/responses/Error412'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'

components:
  securitySchemes:
    $ref: './schemas/security.yaml#/securitySchemes'
