on:
  push:
    branches: ["main"]
  pull_request:

name: Validate

env:
  GOPRIVATE: "github.com/eu-sovereign-cloud"

jobs:
  validate:
    name: Validate Specs
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.23.0'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate
        run: cd APISpec; go run github.com/daveshanley/vacuum@latest lint openapi.yaml

