parameters:
  labelSelector:
    in: query
    name: labels
    description: |
      Filter resources by their labels. Multiple filters are combined with comma.
      Filter syntax:
        - Equals: key=value
        - Not equals: key!=value
        - Wildcards: *key*=*value* - matches if at least one pair match
        - Numeric: key>value, key<value, key>=value, key<=value
        - Namespaced key examples: 'monitoring:alert-level=high' or 'billing:team=platform'
    required: false
    schema:
      type: string
      example: "cloud:region=us-east-1,billing:team=platform,tier!=dev"

  limitParam:
    in: query
    name: limit
    description: Maximum number of resources to return in the response
    required: false
    schema:
      type: integer
      minimum: 1
      maximum: 10000
      default: 1000

  skipTokenParam:
    in: query
    name: skipToken
    description: Opaque cursor for pagination. Use the skipToken from the previous response to get the next page of results. Note that skipTokens do not guarantee consistency across pages if the underlying data changes between requests
    required: false
    schema:
      type: string

  ifUnmodifiedSince:
    in: header
    name: if-unmodified-since
    schema:
      type: string
      format: date-time
    required: false
    description: |
      Returns resources only if they have not been modified since the specified time.
      Uses metadata.lastUpdatedTimestamp for comparison.

  acceptHeader:
    in: header
    name: Accept
    schema:
      type: string
      default: application/json
      example: "application/json; deleted=true"
    description: |
      Controls whether deleted resources are included:
      - application/json: Returns only non-deleted resources
      - application/json; deleted=true: Returns both deleted and non-deleted resources
      - application/json; deleted=only: Returns only deleted resources

  tenantID:
    name: id
    in: path
    required: true
    schema:
      type: string
    description: Tenant ID
